<?php

namespace App\Telegram;

use DefStudio\Telegraph\Handlers\WebhookHandler;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Stringable;

class Handler extends WebhookHandler
{
    public function subscribe(): void
    {
        $data    = $this->message->toArray();
        $name    = $data['chat']['title'];
        $chat_id = $data['chat']['id'];
        $type    = $data['chat']['type'];

        $exists = $this->bot
            ->chats()
            ->where('type', $type)
            ->where('chat_id', $chat_id)
            ->exists();

        if ($exists) {
            $this->reply('Этот чат уже подписан на этот бот!');
            return;
        }

        $this->bot->chats()->create(
            [
                'type'    => $type,
                'chat_id' => $chat_id,
                'name'    => $name
            ]
        );

        $this->reply('Этот чат успешно подписан!');
    }

    public function unsubscribe(): void
    {
        $data    = $this->message->toArray();
        $chat_id = $data['chat']['id'];

        $this->bot
            ->chats()
            ->where('chat_id', $chat_id)
            ->delete();

        $this->reply('Этот чат успешно отписан!');
    }

    protected function handleUnknownCommand(Stringable $text): void
    {
        if ($text->value() === '/start') {
            $this->reply('Добро пожаловать! Используйте команды /subscribe для подписки, /unsubscribe для отписки от бота.');
            return;
        }

        parent::handleUnknownCommand($text); // TODO: Change the autogenerated stub
    }
}
